# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
# check for more here https://wowchemy.com/docs/getting-started/customization/

theme: coffee #default = minimal
day_night: true
font: ''
font_size: M #default = L

# SEO

site_type: Person
local_business_type: ''
org_name: ''
description: ''
twitter: ''

# Contact (edit or remove options as required)

email: d.s.ramakant [at] gmail [dot] com
#phone: +91 9820212863
address:
  street: Andheri (W)
  city: Mumbai
  region: Maharashtra
  postcode: '400053'
  country: India
  country_code: IN
coordinates:
  latitude: '19.1136'
  longitude: '72.8697'
directions: 
office_hours:
  - 'Monday 10:00 to 13:00'
  - 'Wednesday 09:00 to 10:00'
appointment_url: 
contact_links:
  - icon: twitter
    icon_pack: fab
    name: Tweet
    link: 'https://twitter.com/ds_ramakant'
  - icon: skype
    icon_pack: fab
    name: Skype Me
    link: 'live:d.s.ramakant'
  # - icon: keybase
  #   icon_pack: fab
  #   name: Chat on Keybase
  #   link: 'https://keybase.io/'
  - icon: github
    icon_pack: fab
    name: Github
    link: 'https://github.com/ds-ramakant'
  - icon: instagram
    icon_pack: fab
    name: IG
    link: 'https://www.instagram.com/ds_ramakant/'

# Site header

main_menu:
  enable: true
  align: l
  show_logo: true
  show_language: false
  show_day_night: true
  show_search: true
  highlight_active_link: true

# Localization

date_format: 'Jan 2, 2006'
time_format: '3:04 PM'
address_format: en-us

# Site features

highlight: true
highlight_languages:
  - r
  - python
  - latex
math: true
diagram: false
privacy_pack: false
edit_page:
  repo_url: ''
  content_dir: ''
  repo_branch: main
  editable:
    page: false
    post: false
    book: false
show_related:
  book: true
  page: false
  post: true
  project: true
  publication: true
  event: true
reading_time: true
section_pager: false
docs_section_pager: true
sharing: true
copyright_license:
  enable: false
  allow_derivatives: false
  share_alike: true
  allow_commercial: false
  notice: 'This work is licensed under {license}'
abstract_length: 135
plugins_js: []
avatar:
  gravatar: false
  shape: circle
publications:
  date_format: January 2006
  citation_style: apa
projects:
  post_view: 2
  publication_view: 2
  talk_view: 2
breadcrumb:
  page_types:
    book: true
comments:
  provider: 'disqus' #default was empty
  commentable:
    post: true
    book: true
    project: true
    publication: true
    event: true
  disqus:
    shortname: 'ds-ramakant'
    show_count: false # Show comment count in page header? default was true
  commento:
    url: ''
search:
  provider: wowchemy
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
map:
  provider: mapnik
  api_key: ''
  zoom: 15
marketing:
  google_analytics: 'G-Z8T5LSBJE1'
  google_tag_manager: 'G-Z8T5LSBJE1'
  google_site_verification: ''
  baidu_site_verification: ''
  baidu_tongji: ''
cms:
  branch: master
  local_backend: false
icon:
  pack:
    ai: false
