---
title: TidyTuesday NYT Bestsellers list
author: ''
date: '2022-06-01'
slug: tidytuesday-nyt-bestsellers-list
categories:
  - tidytuesday
  - R
tags:
  - dataviz
  - tidytuesday
  - ggplot
subtitle: ''
summary: ''
authors: []
lastmod: '2022-08-22T10:32:21+05:30'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

```{r extracting and cleaning, echo=FALSE, warning=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
suppressMessages({
  library(tidyverse)
  library(scales)
  library(knitr)
  library(tidytuesdayR)
  library(forcats)
})

data <- read_tsv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-05-10/nyt_titles.tsv')

```
```{r EDA}
data %>% 
  mutate(decade = factor(10*year %/% 10)) %>% 
  filter(best_rank==1, year<2020) %>% 
  group_by(decade) %>% 
  summarise(n = n_distinct(title)) %>% 
  ggplot(aes(x = decade, y = n))+
  geom_bar(stat = "identity")

data %>% 
  mutate(decade = factor(10*year %/% 10)) %>% 
  filter(year<2020) %>% 
  group_by(decade) %>% 
  ggplot(aes(x = decade, y = total_weeks))+
  geom_boxplot()


data %>% 
  #mutate(decade = factor(10*year %/% 10)) %>% 
  filter(year> 1989) %>% 
  group_by(year) %>% 
  summarise(n = n_distinct(title)) %>% 
  ggplot(aes(x = year, y = n))+
  geom_line()

rank_all <- data %>% 
  #filter(year> 1989) %>% 
  group_by(year) %>% 
  summarise(all_titles = n_distinct(title))

rank_best <-data %>% 
  filter(best_rank ==1) %>% 
  group_by(year) %>% 
  summarise(best_rank_is_1 = n_distinct(title))

table01 <- rank_all %>% 
  left_join(rank_best, by = "year") %>% 
  mutate(success_ratio = best_rank_is_1/all_titles)

#comparing number of titles to the ones that made it top of the charts
table01 %>% 
  ggplot(aes(x = year))+
  geom_line(aes(y = all_titles), color = "red")+
  geom_line(aes(y = best_rank_is_1), color = "blue")+
  scale_x_continuous(breaks = (seq(from = 1930, to = 2020, by = 10)))

#number of best sellers jumped up significantly in the 2000s
#this means that in the 90s there were an avg of 10 best sellers in each each
#but that has changed to 22 during the 2000s and 31 in the 2010s
table01 %>% 
  filter(year<2020) %>% 
  mutate(decade = factor(10*year %/% 10)) %>% 
  ggplot(aes(x = decade, y = best_rank_is_1))+
  geom_boxplot()

##draft table
table01 %>% 
  filter(year<2020) %>% 
  mutate(decade = factor(10*year %/% 10)) %>% 
  group_by(decade) %>% 
  summarise(avg_titles = mean(all_titles),
            avg_best = mean(best_rank_is_1))


#success ratio
table01 %>% 
  ggplot(aes(x = year, y = success_ratio))+
  geom_line()+
  scale_x_continuous(breaks = (seq(from = 1930, to = 2020, by = 10)))

#has this had an impact on the shelf life of books?
data %>%
  mutate(decade = factor(10*year %/% 10)) %>%
  summary()
  


```

